
version: '3'

networks:
  srm:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv4: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16

volumes:
  rabbitmq: {}
  srm_mongodb:
    driver: local

services:

  phone-service:
    image: seller/phone-service:latest
    container_name: seller_phone
    networks:
      srm:
        ipv4_address: 172.32.0.101
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"

  order-service:
    image: seller/order-service:latest
    container_name: seller_order
    networks:
      srm:
        ipv4_address: 172.32.0.106
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://config-server:8080"
      PROFILE: "default"

  config-server:
    image: seller/config-server:latest
    container_name: seller_configserver
    networks:
      srm:
        ipv4_address: 172.32.0.103
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
    volumes:
      - ./src/config:/usr/local/config-repo

  rabbitmq-srm:
    image: rabbitmq:3-management
    container_name: rabbitmq_srm
    networks:
      srm:
        ipv4_address: 172.32.0.104

  service-discovery:
    image: seller/service-discovery:latest
    container_name: seller_servicediscovery
    networks:
      srm:
        ipv4_address: 172.32.0.105
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"

  mongodb:
    image: mongo:3.6.3
    container_name: srm_mongo
    command: --bind_ip_all
    networks:
      srm:
        ipv4_address: 172.32.0.107
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: db_srm
    volumes:
      - ./src/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - srm_mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      srm:
        ipv4_address: 172.32.0.108
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
