version: '3'

networks:
  srm:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv4: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16

services:

  phone-service:
    image: seller/phone-service:latest
    container_name: seller_phone
    networks:
      srm:
        ipv4_address: 172.32.0.101
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
