
version: '3'

networks:
  srm:
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv4: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16

volumes:
  rabbitmq: {}

services:

  phone-service:
    image: seller/phone-service:latest
    container_name: seller_phone
    networks:
      srm:
        ipv4_address: 172.32.0.101
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://config-server:8080"

  store-service:
    image: seller/store-service:latest
    container_name: seller_store
    networks:
      srm:
        ipv4_address: 172.32.0.102
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://config-server:8080"

  config-server:
    image: seller/config-server:latest
    container_name: seller_configserver
    networks:
      srm:
        ipv4_address: 172.32.0.103
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
    volumes:
      - ./src/config:/usr/local/config-repo

  rabbitmq-srm:
    image: rabbitmq:3-management
    container_name: rabbitmq_srm
    networks:
      srm:
        ipv4_address: 172.32.0.104

  service-discovery:
    image: seller/service-discovery:latest
    container_name: seller_servicediscovery
    networks:
      srm:
        ipv4_address: 172.32.0.105
    expose:
      - 8080
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: "local"
      SERVER_PORT: "8080"
